[pytest]
addopts =
    --headed
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure
    --html=reports/report.html
    --self-contained-html
    -v

testpaths = tests
markers =
    smoke: Quick sanity tests (run on every deploy)
    regression: Full regression suite
    login: Login module tests
    employee: Employee module tests
    leave: Leave module tests
